<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

// ─────────────────────────────────────────────────────────────────────────────
// Migration: Add payment_method to orders + source to qr_codes
//
// Run: php artisan migrate
// ─────────────────────────────────────────────────────────────────────────────

return new class extends Migration
{
    public function up(): void
    {
        // ── 1. Add payment_method to orders table ─────────────────────────
        Schema::table('orders', function (Blueprint $table) {
            // 'online' = Razorpay, 'cod' = cash on delivery
            $table->enum('payment_method', ['online', 'cod'])
                ->default('online')
                ->after('payment_status');

            // Ensure paid_at exists (add if missing)
            if (!Schema::hasColumn('orders', 'paid_at')) {
                $table->timestamp('paid_at')->nullable()->after('payment_method');
            }
        });

        // ── 2. Add source to qr_codes table ──────────────────────────────
        Schema::table('qr_codes', function (Blueprint $table) {
            // 'online_order' = auto-assigned via checkout
            // 'bulk_admin'   = generated by admin in bulk and sold separately
            // null           = legacy / unclassified (treated as online_order)
            $table->enum('source', ['online_order', 'bulk_admin'])
                ->nullable()
                ->default(null)
                ->after('order_id');

            $table->index('source');
        });
    }

    public function down(): void
    {
        Schema::table('orders', function (Blueprint $table) {
            $table->dropColumn('payment_method');
        });

        Schema::table('qr_codes', function (Blueprint $table) {
            $table->dropIndex(['source']);
            $table->dropColumn('source');
        });
    }
};
